name: Android Build for Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android.jks

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: autoconf automake build-essential ccache clang cmake gettext git libffi-dev libltdl-dev libssl-dev libtool openssl patch pkg-config unzip zip zlib1g-dev

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: |
            ./build/android/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('tools/build/buildozer.spec') }}

      - name: Buildozer Build
        run: bash tools/build/build_android_release.sh
    
      - name: Sign the APK manually
        run: |
          APK_PATH=$(find ./build/android/bin -name "*-release-unsigned.apk" | head -n 1)
          ${{ github.workspace }}/build/android/.buildozer/android/platform/android-sdk/build-tools/*/apksigner sign --verbose \
            --ks android.jks \
            --ks-pass "pass:${{ secrets.KEYSTORE_PASSWORD }}" \
            --key-pass "pass:${{ secrets.KEY_PASSWORD }}" \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            "$APK_PATH"

      - name: Rename the signed APK
        run: |
          APK_PATH=$(find ./build/android/bin -name "*-release-unsigned.apk" | head -n 1)
          NEW_APK_PATH="${APK_PATH/-unsigned/-signed}"
          mv "$APK_PATH" "$NEW_APK_PATH"

      # Step 5: Upload Signed APK Artifact
      - name: Upload Signed APK Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: signed-release-apk
          path: ./build/android/bin/*-release-signed.apk
